name: ci
on: [push]
jobs:
  build:
    name: website build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout pages
        uses: actions/checkout@v2.3.1

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.2

      - run: pnpm install
      - run: pnpm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
